<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>ReviewHall.Services</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReviewHall.Core\ReviewHall.Core.csproj" />
		<ProjectReference Include="..\ReviewHall.Infrastructure\ReviewHall.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
	</ItemGroup>
</Project>